part of 'auth_bloc.dart';

@freezed
class AuthState with _$AuthState {
  const factory AuthState.initial({
    @Default('--Selected--') String gender,
    CountryResponseEntity? country,
    StateResponseEntity? state,
    String? jsCountry,
    File? file,
    String? errorMessage,
    String? confirmPassword,
    String? countryId,
    String? jsGender,
    @Default('--Selected--') String jobType,
    String? jsState,
    String? city,
    File? picture,
    @Default('--Selected--') String educationalQualification,
    String? dateOFBirth,
    String? startYear,
    String? endYear,
    @Default('--Selected--') String employmentHistory,
    CategoryResponseEntity? category,
    SkillResponseEntity? skills,
    @Default(RegisterEmployerEntity(
      email: '',
      password: '',
      companyName: '',
      city: '',
      confirmPassword: '',
      country: '',
      gender: '',
      officeTitle: '',
      phoneNumber: '',
      state: '',
      fullName: '',
      companyLogo: null,
    ))
    RegisterEmployerEntity registerEmployerRequest,
    @Default(RegisterJobSeekerEntity(
        fullName: '',
        companyName: '',
        state: '',
        city: '',
        confirmPassword: '',
        passport: null,
        resume: null,
        gender: '',
        country: '',
        email: '',
        password: '',
        phoneNumber: '',
        jobType: '',
        guarantorName: '',
        guarantorEmail: '',
        residentialAddress: '',
        streetAddress: '',
        yearsOfExperience: '',
        describeYourRole: '',
        category: '',
        dateOFBirth: '',
        skill: '',
        role: '',
        description: '',
        startYear: '',
        endYear: '',
        schoolName: '',
        educationalQualification: '',
        certificateObtained: '',
        graduationYear: '',
        courseName: '',
        employmentHistory: '',
        guarantorPhoneNumber: ''))
    RegisterJobSeekerEntity registerJobSeekerRequest,
    File? resume,
    @Default([]) List<StateResponseEntity> states,
    @Default(['--Selected--', 'Male', 'Female', 'Other']) List<String> genders,
    @Default([
      'No Education',
      'FLSC',
      'WAEC',
      'NECO',
      'GCE',
      'B.sc',
      'M.sc',
      'Phd',
      'B. Tech'
    ])
    List<String> levelOfEducation,
    @Default(['Employment History', 'No Employment History'])
    List<String> employmentHistoryType,
    @Default(["--Select--", "Full Time", "Tempoary", "Contract", "Part Time"])
    List<String> workMode,
    @Default([]) List<CountryResponseEntity> countries,
    @Default([]) List<CategoryResponseEntity> categoryList,
    @Default([]) List<SkillResponseEntity> skill,
    @Default(false) bool isChecked,
    @Default(ViewState.idle) ViewState viewState,
  }) = _Initial;
}
